In [15]:
import tensorflow as tf
from keras import layers
import numpy as np

In [16]:
inputs = layers.Input(shape=(8,))
#hidden = hl(inputs)
outputs = layers.Dense(3, activation="tanh")(inputs)
model1 = tf.keras.Model(inputs, outputs)
#hl.set_weights([np.eye(num_states), np.zeros(num_states,)])

In [32]:
inputs = layers.Input(shape=(8,))
h = layers.Dense(5, activation="relu", kernel_initializer=tf.keras.initializers.Zeros())(inputs)
con = layers.Concatenate()([inputs, h])
lay = layers.Dense(3, activation="tanh")
outputs = lay(con)        
model2 = tf.keras.Model(inputs, outputs)

In [19]:
model1.get_weights()

[array([[-0.34780475,  0.04206604, -0.1699825 ],
        [ 0.54741865,  0.6049331 ,  0.5859371 ],
        [ 0.23449904, -0.25938004,  0.61023086],
        [-0.6897001 , -0.14754856, -0.31623802],
        [ 0.4345892 , -0.3627083 , -0.28956327],
        [-0.07949144,  0.3933298 , -0.60756075],
        [-0.2946713 , -0.58233213, -0.15249085],
        [-0.10806823,  0.12814587,  0.30159825]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [21]:
model2.get_weights()

[array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.2349579 ,  0.37419713,  0.06228882],
        [-0.01714957, -0.26259705,  0.24705642],
        [-0.14790294,  0.2511075 , -0.18654528],
        [ 0.37092435,  0.60641366, -0.12762251],
        [-0.56731117, -0.18455514, -0.53774613],
        [-0.03094184, -0.5824338 ,  0.4426853 ],
        [-0.47767708, -0.14015335,  0.59356624],
        [ 0.39624995, -0.32526127, -0.00212872],
        [ 0.27206796,  0.05536884,  0.12278783],
        [-0.49297214, -0.08867455,  0.04409873],
        [-0.16277808, -0.56035084, -0.3336414 ],
        [ 0.05574012, -0.06011879, -0.27035278],
        [-0.4678582 , -0.48724598, -0.16313505]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [24]:
a =  model1.get_weights()[0]

In [30]:
b = np.concatenate([a, np.zeros((5,3))], axis = 0)

In [31]:
b

array([[-0.34780475,  0.04206604, -0.16998249],
       [ 0.54741865,  0.60493308,  0.58593708],
       [ 0.23449904, -0.25938004,  0.61023086],
       [-0.68970013, -0.14754856, -0.31623802],
       [ 0.43458921, -0.3627083 , -0.28956327],
       [-0.07949144,  0.3933298 , -0.60756075],
       [-0.2946713 , -0.58233213, -0.15249085],
       [-0.10806823,  0.12814587,  0.30159825],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [35]:
lay.set_weights([b, model1.get_weights()[1]])

In [36]:
model2.get_weights()

[array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.34780475,  0.04206604, -0.1699825 ],
        [ 0.54741865,  0.6049331 ,  0.5859371 ],
        [ 0.23449904, -0.25938004,  0.61023086],
        [-0.6897001 , -0.14754856, -0.31623802],
        [ 0.4345892 , -0.3627083 , -0.28956327],
        [-0.07949144,  0.3933298 , -0.60756075],
        [-0.2946713 , -0.58233213, -0.15249085],
        [-0.10806823,  0.12814587,  0.30159825],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]